apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-add-k8s-labels-annotations
spec:
  package: c8n.io/aghilish/function-add-k8s-labels-annotations:v0.0.2
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0
